# This file generated by make-makefile.sh, do not edit!
# Create Makefile-include.txt instead for your customizations.
CC := gcc
override CFLAGS += -Wall -Werror -g -fmax-errors=99 -Wuninitialized -Wmissing-prototypes -Wredundant-decls -Wno-unused-result -O2 -I/usr/local/include
LIBS := -L/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -leps -lhsl_ma48 -lblas -lgfortran -lm -lquadmath

.PHONY: all
all:
	make  main.exe power_system_functions.o

#include Makefile-include.txt

.PHONY: test
test: main.exe
	./main.exe


.PHONY: mem_test
mem_test: main.exe
	valgrind --tool=memcheck ./main.exe


.PHONY: clean
clean:
	rm -f *.o *.exe *.stackdump main

main.o: main.c power_system_functions.h
	$(CC) $(CFLAGS) -c main.c -o main.o

main.exe: main.o power_system_functions.o sa_power.o
	$(CC) $(CFLAGS) -o main.exe  main.o power_system_functions.o sa_power.o $(LIBS) 

power_system_functions.o: power_system_functions.c power_system_functions.h
	$(CC) $(CFLAGS) -c power_system_functions.c -o power_system_functions.o

sa_power.o: sa_power.c power_system_functions.h
	$(CC) $(CFLAGS) -c sa_power.c -o sa_power.o

# Checksum of the original file: 2833053967
